models/User.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use app\extras\personal;

class User extends ActiveRecord {
	// public $id;
	// public $first_name;
	// public $last_name;
	// public $email;
	// public $personal_code;
	// public $phone;
	// public $active;
	// public $dead;
	// public $lang;
	/**
	 * @inheritdoc
	 */
	public static function tableName() {
		return 'user';
	}
	public function rules() {
		return [ 
				[ 
						[ 
								'first_name',
								'last_name',
								'email',
								'personal_code',
								'phone',
								'lang' 
						
						],
						'required' 
				],
				[ 
						[ 
								'first_name',
								'last_name',
								'email',
								'lang' 
						],
						'string' 
				],
				[ 
						[ 
								'personal_code',
								'phone' 
						],
						'integer' 
				],
				[ 
						[ 
								'dead',
								'active' 
						],
						'boolean' 
				],
				[ 
						[ 
								'email' 
						],
						'email' 
				],
				[ 
						[ 
								'personal_code' 
						],
						'validatePersonalCode' 
				],
				[ 
						[ 
								'personal_code' 
						],
						'unique',
						'targetAttribute' => 'personal_code' 
				] 
		];
	}
	/**
	 * get loan details
	 *
	 * @return \yii\db\ActiveQuery
	 */
	public function getLoans() {
		return $this->hasMany ( Loan::className (), [ 
				'user_id' => 'id' 
		] )->inverseOf ( 'user' );
	}
	/**
	 * validate personal code
	 */
	public function validatePersonalCode($attribute, $value) {
		$validate = personal::validatePersonalCode ( $this->$attribute );
		if ($validate !== true) {
			$this->addError ( $attribute, 'Personal code is Invalid' );
		}
	}
	/**
	 * get user age
	 *
	 * @return array
	 */
	public function getAge() {
		return personal::getAgeByPersonalCode ( $this->personal_code );
	}
}

controllers/loanController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Loan;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoanSearch;
use app\models\User;

class LoanController extends Controller {
	public function behaviors() {
		$this->enableCsrfValidation = false;
		
		return [ 
				'verbs' => [ 
						'class' => VerbFilter::className (),
						'actions' => [ 
								'delete' => [ 
										'get',
										'post' 
								] 
						] 
				] 
		];
	}
	/**
	 * display loan view page
	 *
	 * @return array loan details to gridview
	 */
	public function actionLoans() {
		$model = new LoanSearch ();
		$dataprovider = $model->search ( Yii::$app->request->queryParams );
		return $this->render ( 'loans', [ 
				'model' => $model,
				'dataprovider' => $dataprovider 
		] );
	}
	/**
	 * Displays a single Loan model.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionView($id) {
		$loan = $this->findModel ( $id );
		// var_dump ( $loan );
		return $this->render ( 'view', [ 
				'model' => $loan,
				'user' => $loan->user 
		] );
	}
	/**
	 * Creates a new Loan model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new Loan ();
		$valPost = Yii::$app->request->post ();
		if (count ( $valPost ) !== 0) {
			$user_id = $valPost ['Loan'] ['user_id'];
			$tempModel = User::findOne ( $user_id );
			if ($tempModel === null) {
				/* user id not present hence cannot create loan */
				return $this->render ( 'create', [ 
						'model' => $model,
						'showUserId' => true,
						'errorMsg' => 'User Id not available. Please Create User First' 
				] );
			} else {
				if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {
					/* successfull creation of loan redirect to view page */
					return $this->redirect ( [ 
							'view',
							'id' => $model->id 
					] );
				} else {
					/* unsuccessfull creation of loan renders to same page */
					return $this->render ( 'create', [ 
							'model' => $model,
							'showUserId' => true,
							'errorMsg' => '' 
					] );
				}
			}
		} else {
			/* creating new loan */
			return $this->render ( 'create', [ 
					'model' => $model,
					'showUserId' => true,
					'errorMsg' => '' 
			] );
		}
	}
	/**
	 * Updates an existing Loan model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionUpdate($id) {
		$model = $this->findModel ( $id );
		if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {
			/* successfully updation of loan redirect to view page */
			return $this->redirect ( [ 
					'view',
					'id' => $model->id 
			] );
		} else {
			/* unsuccessfull updation of loan renders the same page */
			return $this->render ( 'update', [ 
					'model' => $model,
					'showUserId' => true,
					'errorMsg' => '' 
			] );
		}
	}
	
	/**
	 * Deletes an existing Loan model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionDelete($id) {
		$user = $this->findModel ( $id );
		$user->delete ();
		return $this->redirect ( [ 
				'loans' 
		] );
	}
	/**
	 * Finds the Loan model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id        	
	 * @return Loan the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id) {
		if (($model = Loan::findOne ( $id )) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException ( 'The requested page does not exist.' );
		}
	}
}

controllers/userController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\filters\VerbFilter;
use yii\web\Controller;
use app\models\UserSearch;

class UserController extends Controller {
	public function behaviors() {
		$this->enableCsrfValidation = false;
		return [ 
				'verbs' => [ 
						'class' => VerbFilter::className (),
						'actions' => [ 
								'delete' => [ 
										'post',
										'get' 
								] 
						] 
				] 
		];
	}
	/**
	 * Displays user page
	 *
	 * @return array user details gridview
	 *        
	 */
	public function actionUsers() {
		$model = new UserSearch ();
		$dataprovider = $model->search ( Yii::$app->request->queryParams );
		return $this->render ( 'users', [ 
				'model' => $model,
				'dataprovider' => $dataprovider 
		] );
	}
	/**
	 * Displays a single User model.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionView($id) {
		$user = $this->findModel ( $id );
		return $this->render ( 'view', [ 
				'model' => $user,
				'userAge' => $user->getAge (),
				'loans' => $user->loans 
		] );
	}
	/**
	 * Creates a new User model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new User ();
		if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {			
			return $this->redirect ( [ 
					'view',
					'id' => $model->id 
			] );
		} else {
			return $this->render ( 'create', [ 
					'model' => $model 
			] );
		}
	}
	
	/**
	 * Updates an existing User model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionUpdate($id) {
		$model = $this->findModel ( $id );
		
		if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {
			return $this->redirect ( [ 
					'view',
					'id' => $model->id 
			] );
		} else {
			return $this->render ( 'update', [ 
					'model' => $model 
			] );
		}
	}
	
	/**
	 * Deletes an existing User model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionDelete($id) {
		$user = $this->findModel ( $id );
		$user->delete ();
		return $this->redirect ( [ 
				'users' 
		] );
	}
	/**
	 * Finds the User model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id        	
	 * @return User the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id) {
		if (($model = User::findOne ( $id )) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException ( 'The requested page does not exist.' );
		}
	}
}

views/user/create.php
<?php
$this->title = 'Create User';
$this->params ['breadcrumbs'] [] = [ 
		'label' => 'Users',
		'url' => [ 
				'users' 
		] 
];
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div>
    <?=$this->render ( 'usersedit', [ 'model' => $model ] )?>
</div>

views/user/update.php
<?php
$this->title = 'Update User : ' . ' ' . $model->id;
$this->params ['breadcrumbs'] [] = [ 
		'label' => 'Users',
		'url' => [ 
				'users' 
		] 
];
$this->params ['breadcrumbs'] [] = [ 
		'label' => $model->id,
		'url' => [ 
				'view',
				'id' => $model->id 
		] 
];
$this->params ['breadcrumbs'] [] = 'Update';
?>
<div>	
    <?=$this->render ( 'usersedit', [ 'model' => $model ] )?>
</div>

views/user/users.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
$this->title = 'Users';
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div class="site-about">
	<h1><?= Html::encode($this->title) ?></h1>

	<div class="body-content">
		<div class="row">
			<div class="col-lg-12">
			 <?php
				$form = ActiveForm::begin ( [ 
						'action' => [ 
								'users' 
						],
						'method' => 'get' 
				] );
				?>
    <p>
        <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
    </p>
    <?=GridView::widget ( [ 'dataProvider' => $dataprovider,'filterModel' => $model,'columns' => [ [ 'class' => 'yii\grid\SerialColumn' ],'id','first_name:ntext','last_name:ntext','personal_code','phone',[ 'class' => 'yii\grid\ActionColumn' ] ] ] );?>
    <?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

views/user/usersedit.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<div class="panel-group">
	<div class="panel panel-warning">
		<div class="panel-heading"><?= Html::encode($this->title) ?></div>
	  <?php $form = ActiveForm::begin(['id' => 'user-edit']); ?>
		<div class="panel-body">              
              <?= $form->field($model, 'first_name')->label('First Name')->textInput(['style' => '', 'maxlength' => 255])?>
              
              <?= $form->field($model, 'last_name')->label('Last Name')->textInput(['style' => '', 'maxlength' => 255])?>                    

              <?= $form->field($model, 'email')->label('E-mail')->textInput(['style' => '', 'maxlength' => 255])?>                   

              <?=$form->field ( $model, 'phone' )->label('Phone Number')->textInput(['style' => '', 'maxlength' => 20])?>                                                                                                                                                     			              
              
              <?= $form->field($model, 'personal_code')->label('Personal Code')->textInput(['style' => '', 'maxlength' => 11])?>
              
              <?=$form->field ( $model, 'lang' )->label('Language')->dropDownList (['est' => 'Estonian', 'rus' => 'Russian','eng'=>'English'],['prompt'=>'Select Language'])?>
              
              <?=$form->field($model, 'active')->checkbox();?>
              
              <?=$form->field($model, "dead")->checkbox();?>              
              
              <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-danger']) ?>
        </div>
         <?php ActiveForm::end(); ?>
	</div>
</div>

views/user/view.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
$this->title = $model->id;
$this->params ['breadcrumbs'] [] = [ 
		'label' => 'Users',
		'url' => [ 
				'users' 
		] 
];
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div>
	<h1>User <?= Html::encode($this->title) ?></h1>
	<div>
		<p>
            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            
            <?=Html::a ( 'Delete', [ 'delete','id' => $model->id ], [ 'class' => 'btn btn-danger','data' => [ 'confirm' => 'Are you sure you want to delete this user?','method' => 'post' ] ] )?>
            
            <?= Html::a('Create Loan', ['loan/create', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        </p>

        <?=DetailView::widget ( [ 'model' => $model,'attributes' => [ 'id','personal_code','first_name:ntext','last_name:ntext',[ 'label' => 'Age','value' => $userAge ],'email:email','phone','active:boolean','dead:boolean','lang:ntext',[ 'label' => 'Loans count','format' => 'raw','value' => Html::a ( count ( $loans ), [ 'loan/loans','LoanSearch[user_id]' => $model->id ] ) ] ] ] )?>
    </div>
</div>