models/Loan.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

class Loan extends ActiveRecord {
	
	/**
	 * @inheritdoc
	 */
	public static function tableName() {
		return 'loan';
	}
	public function rules() {
		return [ 
				[ 
						[ 										
								'user_id',
								'amount',
								'interest',
								'duration',
								'start_date',
								'end_date',
								'campaign',
								'status' 
						],
						'required' 
				],
				[ 
						[ 								
								'user_id',
								'duration',
								'campaign',
								'status' 
						],
						'integer' 
				],
				[ 
						[ 
								'amount',
								'interest' 
						],
						'double' 
				],
				[ 
						[ 
								'start_date',
								'end_date' 
						],
						'match',
						'pattern' => '/^\d\d\d\d-\d\d-\d\d$/' 
				] 
		];
	}
	/**
	 *
	 * @return \yii\db\ActiveQuery
	 */
	public function getUser() {
		return $this->hasOne ( User::className (), [ 
				'id' => 'user_id' 
		] );
	}
}

controllers/loanController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Loan;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoanSearch;
use app\models\User;

class LoanController extends Controller {
	public function behaviors() {
		$this->enableCsrfValidation = false;
		
		return [ 
				'verbs' => [ 
						'class' => VerbFilter::className (),
						'actions' => [ 
								'delete' => [ 
										'get',
										'post' 
								] 
						] 
				] 
		];
	}
	/**
	 * display loan view page
	 *
	 * @return array loan details to gridview
	 */
	public function actionLoans() {
		$model = new LoanSearch ();
		$dataprovider = $model->search ( Yii::$app->request->queryParams );
		return $this->render ( 'loans', [ 
				'model' => $model,
				'dataprovider' => $dataprovider 
		] );
	}
	/**
	 * Displays a single Loan model.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionView($id) {
		$loan = $this->findModel ( $id );
		// var_dump ( $loan );
		return $this->render ( 'view', [ 
				'model' => $loan,
				'user' => $loan->user 
		] );
	}
	/**
	 * Creates a new Loan model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new Loan ();
		$valPost = Yii::$app->request->post ();
		if (count ( $valPost ) !== 0) {
			$user_id = $valPost ['Loan'] ['user_id'];
			$tempModel = User::findOne ( $user_id );
			if ($tempModel === null) {
				/* user id not present hence cannot create loan */
				return $this->render ( 'create', [ 
						'model' => $model,
						'showUserId' => true,
						'errorMsg' => 'User Id not available. Please Create User First' 
				] );
			} else {
				if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {
					/* successfull creation of loan redirect to view page */
					return $this->redirect ( [ 
							'view',
							'id' => $model->id 
					] );
				} else {
					/* unsuccessfull creation of loan renders to same page */
					return $this->render ( 'create', [ 
							'model' => $model,
							'showUserId' => true,
							'errorMsg' => '' 
					] );
				}
			}
		} else {
			/* creating new loan */
			return $this->render ( 'create', [ 
					'model' => $model,
					'showUserId' => true,
					'errorMsg' => '' 
			] );
		}
	}
	/**
	 * Updates an existing Loan model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionUpdate($id) {
		$model = $this->findModel ( $id );
		if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {
			/* successfully updation of loan redirect to view page */
			return $this->redirect ( [ 
					'view',
					'id' => $model->id 
			] );
		} else {
			/* unsuccessfull updation of loan renders the same page */
			return $this->render ( 'update', [ 
					'model' => $model,
					'showUserId' => true,
					'errorMsg' => '' 
			] );
		}
	}
	
	/**
	 * Deletes an existing Loan model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionDelete($id) {
		$user = $this->findModel ( $id );
		$user->delete ();
		return $this->redirect ( [ 
				'loans' 
		] );
	}
	/**
	 * Finds the Loan model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id        	
	 * @return Loan the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id) {
		if (($model = Loan::findOne ( $id )) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException ( 'The requested page does not exist.' );
		}
	}
}

controllers/userController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use yii\filters\VerbFilter;
use yii\web\Controller;
use app\models\UserSearch;

class UserController extends Controller {
	public function behaviors() {
		$this->enableCsrfValidation = false;
		return [ 
				'verbs' => [ 
						'class' => VerbFilter::className (),
						'actions' => [ 
								'delete' => [ 
										'post',
										'get' 
								] 
						] 
				] 
		];
	}
	/**
	 * Displays user page
	 *
	 * @return array user details gridview
	 *        
	 */
	public function actionUsers() {
		$model = new UserSearch ();
		$dataprovider = $model->search ( Yii::$app->request->queryParams );
		return $this->render ( 'users', [ 
				'model' => $model,
				'dataprovider' => $dataprovider 
		] );
	}
	/**
	 * Displays a single User model.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionView($id) {
		$user = $this->findModel ( $id );
		return $this->render ( 'view', [ 
				'model' => $user,
				'userAge' => $user->getAge (),
				'loans' => $user->loans 
		] );
	}
	/**
	 * Creates a new User model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new User ();
		if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {			
			return $this->redirect ( [ 
					'view',
					'id' => $model->id 
			] );
		} else {
			return $this->render ( 'create', [ 
					'model' => $model 
			] );
		}
	}
	
	/**
	 * Updates an existing User model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionUpdate($id) {
		$model = $this->findModel ( $id );
		
		if ($model->load ( Yii::$app->request->post () ) && $model->save ()) {
			return $this->redirect ( [ 
					'view',
					'id' => $model->id 
			] );
		} else {
			return $this->render ( 'update', [ 
					'model' => $model 
			] );
		}
	}
	
	/**
	 * Deletes an existing User model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id        	
	 * @return mixed
	 */
	public function actionDelete($id) {
		$user = $this->findModel ( $id );
		$user->delete ();
		return $this->redirect ( [ 
				'users' 
		] );
	}
	/**
	 * Finds the User model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param integer $id        	
	 * @return User the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id) {
		if (($model = User::findOne ( $id )) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException ( 'The requested page does not exist.' );
		}
	}
}

views/loan/create.php
<?php
$this->title = 'Create Loan';
$this->params ['breadcrumbs'] [] = [ 
		'label' => 'Loans',
		'url' => [ 
				'loans' 
		] 
];
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div>	
    <?=$this->render ( 'loansedit', [ 'model' => $model,'showUserId' => $showUserId,'errorMsg'=>$errorMsg] )?>
</div>

views/loan/loans.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;

$this->title = 'Loans';
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div>
	<h1><?= Html::encode($this->title) ?></h1>
	<div class="body-content">
		<div class="row">
			<div class="col-lg-12">
		 <?php
			$form = ActiveForm::begin ( [ 
					'action' => [ 
							'loans' 
					],
					'method' => 'get' 
			] );
			?>
     <p>
        <?= Html::a('Create Loan', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
     </p>
    <?=GridView::widget ( [ 'dataProvider' => $dataprovider,'filterModel' => $model,'columns' => [ [ 'class' => 'yii\grid\SerialColumn' ],'id','user_id','amount','interest','duration',[ 'attribute' => 'start_date','format' => [ 'date','php:d.m.Y' ] ],[ 'class' => 'yii\grid\ActionColumn' ] ] ] );?>
    <?php ActiveForm::end(); ?>
           </div>
		</div>
	</div>
</div>

views/loan/loansedit.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$sValue = Yii::$app->request->get ( 'id' );
?>

<div class="panel-group">
	<div class="panel panel-warning">
		<div class="panel-heading"><?= Html::encode($this->title) ?></div>
		<div class="panel-body">
		   <?php $form = ActiveForm::begin(['id' => 'loans-edit']); ?>
		   <?php if ($showUserId === false) {?>		     
			  <?=$form->field ( $model, 'user_id' )->textInput ( [ 'readonly' => 'readonly','maxlength'=>20 ] )->label ( 'User Id' )?>                              
           <?php }else{?>
              <?php if(!empty($sValue)){?>        
              <?= $form->field($model, 'user_id')->textInput ( [ 'readonly' => 'readonly','maxlength'=>20,'value'=>$sValue ] )->label ( 'User Id' )?>
              <?php }else{?>
              <?= $form->field($model, 'user_id')->label('User Id')->textInput(['maxlength'=>20])?>
              <?php }?>                                                           
           <?php }?>
           
              <?= $form->field($model, 'amount')->label('Amount')->textInput(['maxlength'=>20])?>
              
              <?= $form->field($model, 'interest')->label('Interest')->textInput(['maxlength'=>20])?>  
              
              <?= $form->field($model, 'duration')->label('Duration')->textInput(['maxlength'=>4])?>                 

              <?=$form->field ( $model, 'start_date' )->label('Start Date')->textInput(['maxlength'=>10,'type'=>'date'])?>
              
              <?=$form->field ( $model, 'end_date' )->label('End Date')->textInput(['maxlength'=>10,'type'=>'date'])?>                                                                                                                           
                                       
              <?=$form->field($model, "campaign")->label('Campaign')->textInput(['maxlength'=>2])?>
               
              <?=$form->field($model, "status")->label('Status')->textInput(['maxlength'=>2])?>
              
              <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-danger']) ?>
               
               <label><?php echo $errorMsg; ?></label>        
              <?php  ActiveForm::end(); ?> 
		</div>
	</div>
</div>

views/loan/update.php
<?php
$this->title = 'Update Loan : ' . ' ' . $model->id;
$this->params ['breadcrumbs'] [] = [ 
		'label' => 'Loans',
		'url' => [ 
				'loans' 
		] 
];
$this->params ['breadcrumbs'] [] = [ 
		'label' => $model->id,
		'url' => [ 
				'view',
				'id' => $model->id 
		] 
];
$this->params ['breadcrumbs'] [] = 'Update';
?>
<div>	
    <?=$this->render ( 'loansedit', [ 'model' => $model,'showUserId' => $showUserId,'errorMsg' => $errorMsg ] )?>
</div>

views/loan/view.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;

$this->title = $model->id;
$this->params ['breadcrumbs'] [] = [ 
		'label' => 'Loans',
		'url' => [ 
				'loans' 
		] 
];
$this->params ['breadcrumbs'] [] = $this->title;

?>
<div>
	<h1>Loan <?= Html::encode($this->title) ?></h1>
	<div>
		<p>
            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            
            <?=Html::a ( 'Delete', [ 'delete','id' => $model->id ], [ 'class' => 'btn btn-danger','data' => [ 'confirm' => 'Are you sure you want to delete this item?','method' => 'post' ] ] )?>
        </p>

        <?=DetailView::widget ( [ 'model' => $model,'attributes' => [ 'id',[ 'label' => 'User ID','format' => 'raw','value' => Html::a ( $model->user_id, [ 'user/view','id' => $model->user_id ] ) ],[ 'label' => 'Personal Code','value' => $user->personal_code ],[ 'label' => 'First Name','value' => $user->first_name ],[ 'label' => 'Last Name','value' => $user->last_name ],'amount','interest','duration',[ 'attribute' => 'start_date','format' => [ 'date','php:d.m.Y' ] ],[ 'attribute' => 'end_date','format' => [ 'date','php:d.m.Y' ] ],'campaign','status' ] ] )?>
        
    </div>

</div>